name: pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Static Web App
        run: npm run build -- --base=$BASE_URL
        env:
          BASE_URL: anyonecancode
          VITE_FACE_API_KEY: ${{ secrets.VITE_FACE_API_KEY }}
          VITE_SPEECH_API_KEY: ${{ secrets.VITE_SPEECH_API_KEY }}
          VITE_IMAGE_API_URL: ${{secrets.VITE_IMAGE_API_URL}}
          VITE_FACE_API_ENDPOINT: ${{secrets.VITE_FACE_API_ENDPOINT}}
          VITE_VISION_API_ENDPOINT: ${{secrets.VITE_VISION_API_ENDPOINT}}
          VITE_VISION_API_KEY: ${{secrets.VITE_VISION_API_KEY}}
        working-directory: frontend

      - name: Upload result of Static Web App build
        uses: actions/upload-artifact@v3
        with:
          name: static-webapp
          path: frontend/dist
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-app
    environment:
      name: pages
      url: https://${{ github.repository_owner }}.github.io/anyonecancode
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    if: github.ref == 'refs/heads/main'

    steps:
#       - name: Download build of static app
#         uses: actions/download-artifact@v3
#         with:
#           name: static-webapp
#           path: frontend/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
